export const ROUTES = {
  landing: "/",
  login: "/login",
  dashboard: "/dashboard",
  inbox: "/invoices",
  invoiceDetail: (id: string) => `/invoices/${id}`,
  compareView: (id: string) => `/invoices/${id}/compare`,
  exceptions: "/exceptions",
  purchaseOrders: "/purchase-orders",
  deliveryReceipts: "/delivery-receipts",
  vendors: "/vendors",
  pipeline: "/pipeline",
  flow: "/flow",
  settings: "/settings",
} as const
